version: '3'
services:
  node-app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8080:5000
    env_file: .env
    environment:
      - app_password=1234
      - PORT=5000
      - NODE_ENV=development
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    networks:
      - node_net
  db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - ./mongo_backup:/data/db
    networks:
      - node_net

networks:
  node_net:
    driver: bridge